---
- name: Create zabbix directory
  win_file:
    path: 'C:\Zabbix'
    state: directory

- name: Fact for 32 arch
  set_fact:
    win_arch_fact: 32

- name: Update fact for 64 arch
  set_fact:
    win_arch_fact: 64
  when: (ansible_architecture == '64-bit' or ansible_architecture == '64-разрядная')

- import_tasks: version3.yml
  when: (zabbix_agent_version == '3')

- import_tasks: version4.yml
  when: (zabbix_agent_version == '4')

- name: Add firewall rule for {{ zabbix_agent_port }} port
  win_firewall_rule:
    name: 'Zabbix-Agent'
    localport: '{{ zabbix_agent_port }}'
    action: allow
    direction: in
    protocol: tcp
    remoteip: '{{ zabbix_server_ip }}'
    state: present
    enabled: yes